# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Personal academic website of Saraf Anzum Shreya, showcasing research in machine learning and assistive technologies.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: 'Saraf Anzum Shreya'

# Site footer
footer:
  copyright:
    notice: '© {year} Saraf Anzum Shreya. All rights reserved.' # Corrected typo from Shreyal to Shreya
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

# Assets (for favicon)
params:
  assets:
    favicon: '/favicon.ico'          # Main favicon
    favicon_16x16: '/images/favicon-16x16.png'  # Optional smaller size
    favicon_32x32: '/images/favicon-32x32.png'  # Optional larger size
    apple_touch_icon: '/images/apple-touch-icon.png'  # Optional for Apple devices